### ISSUE TITLE
Is there a way to remove a child from a parent element?

### ISSUE THREAD

**Issue by alessioarena** [python-visualization/branca#107]
In the past to remove an Element or MacroElement from its parent I used `del parent._children[childName]`, but that seems a buggy operation.
In several cases when rendering the parent the child is still there.

Is there a preferred way to remove a child from a parent element?

An example of the issue I'm having:
Adding a Draw element to a Leaflet map using Folium
![image](https://user-images.githubusercontent.com/33886395/153136660-7c0d8196-e40a-414f-b1f2-2482856600ec.png)

Parent has the `draw_control` child
![image](https://user-images.githubusercontent.com/33886395/153136897-84834d34-c645-40be-913f-c1b66564046a.png)

JavaScript code injected to the resulting HTML element
![image](https://user-images.githubusercontent.com/33886395/153136815-1af3b5a3-e4d4-4672-82c5-64d09f28527e.png)

Now I removed the child from the `_children` attribute using the method above:
![image](https://user-images.githubusercontent.com/33886395/153137004-01cfb608-f964-4c8c-9bee-5df689752ef0.png)

The Draw element is still there when rendering!
![image](https://user-images.githubusercontent.com/33886395/153137142-1387b31b-7046-4468-82f4-c5ae45f3e2d9.png)

and the JavaScript code is still there

**Comment by RohanG0407** [comment]
@alessioarena Any solution to this issue yet?

**Comment by alessioarena** [comment]
Unfortunately not at the moment. I think is something to do with the rendering of the leaflet map already done once with the child, and probably cached somewhere. However I could not find a solution apart from copying the children and attribute of the map to another brand new Map object. I can send you the snippet of code that worked for me if that is helpful

**Comment by alessioarena** [comment]
This is what I'm currently doing to copy a Map object:
```Python
def copy_map(map_obj):
    new_map = folium.Map()
    new_map.options = map_obj.options
    for k, v in map_obj._children.items():
        new_map.add_child(v)
    return new_map
```

You can then remove the child before is rendered, or just not add it in the first place by modifying this function and capturing a condition (child name, index and so on).

I'm not sure if that is generalized enough, there may be other attributes that you would like to copy to the new object, but for my case it worked

**Comment by Conengmo** [comment]
When we render, objects are added to the `header`, `html` and `script` attributes of the `Figure` object. To delete something, it has to be deleted there as well.

The way things are set up pretty much assumes a user renders once and that's it.

Thanks for sharing your workaround @alessioarena. I'll close the issue for now. If somebody wants to think about a cleaner, native way of deleting items, that's welcome.
