### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jmcarp** [python-visualization/branca#108]
It would be great if you all could cut a new release at some point. I spent some time debugging an incompatibility with the `data-html` attribute related to [fastpages](https://github.com/fastai/fastpages), but the new `srcdoc` approach looks simpler.

**Comment by Conengmo** [comment]
Totally right. It's been long enough that we can assume the `srcdoc` usage didn't cause any issues for our users using the main branch.

@ocefpaf can you make a release? This would be version 0.5.0. I've already update the changelog. https://github.com/python-visualization/branca/blob/master/CHANGES.txt

**Comment by ocefpaf** [comment]
Done: https://github.com/python-visualization/branca/releases/tag/v0.5.0

PyPI and conda-forge release will be up soon.
