### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/branca#118]
@Conengmo are you ok with this? If so, let me know and I can do that and adapt the CIs.

**Comment by Conengmo** [comment]
Yes, good idea. We should update the link in the readme afterwards, but that should be it.

**Comment by ocefpaf** [comment]
Done!

**Comment by Conengmo** [comment]
I updated the readme

**Comment by ocefpaf** [comment]
> I updated the readme

Thanks!
