### ISSUE TITLE
How to show latex caption?

### ISSUE THREAD

**Issue by zxdawn** [python-visualization/branca#139]
```
from branca.colormap import linear

colormap_choice = linear.YlOrRd_04
vmin = 3.2
vmax = 10.3
colormap = colormap_choice.scale(vmin, vmax)
colormap.caption = '$\Delta$ x'
colormap
```

<img width="508" alt="image" src="https://github.com/python-visualization/branca/assets/30388627/ee928d7c-ea1a-48c6-a262-c654137d28bd">

It seems the latex symbol $\Delta$ is neglected.

**Comment by zxdawn** [comment]
Well, I can use html sybol insead of latex: `'&Delta;x'`:

<img width="517" alt="image" src="https://github.com/python-visualization/branca/assets/30388627/3e5d4ace-0029-4263-beb8-622d24ac95b1">

**Comment by ocefpaf** [comment]
`branca` doesn't ship any math JS libraries, only basic HTML is supported. One can easily write a plugin for Mathjax, etc though. I'm closing this b/c it is not in the scope of `branca`.

**Comment by zxdawn** [comment]
Thanks for your reply. I realize that `'&Delta;x'` works for the colormap caption. However, if I add it to folium map, it's not rendered:

```
from branca.colormap import linear
import folium

colormap_choice = linear.YlOrRd_04
vmin = 3.2
vmax = 10.3
colormap = colormap_choice.scale(vmin, vmax)
colormap.caption = '&Delta;x'

m = folium.Map()
colormap.add_to(m)
```

<img width="687" alt="image" src="https://github.com/python-visualization/branca/assets/30388627/a014d852-57e2-4563-851c-2248325ed499">

Any idea of this?

**Comment by ocefpaf** [comment]
Most likely a bug in folium. Do you mind opening this issue there?

**Comment by zxdawn** [comment]
Got it. Posted [here](https://github.com/python-visualization/folium/issues/1809).
