### ISSUE TITLE
rendering utf-8 with Iframe

### ISSUE THREAD

**Issue by knil-sama** [python-visualization/branca#15]
Hi everyone,

When I put html in my popup on folium using the IFrame element, I got the following issue with utf-8 encoded text.
![bad_folium_rendering](https://cloud.githubusercontent.com/assets/2539833/16980025/7cd1571a-4e64-11e6-8d05-0b9e68871584.PNG)
I tracked the issue and find that the charset was missing in the html part of the iframe, after I put it I got the expected result.
![good_folium_rendering](https://cloud.githubusercontent.com/assets/2539833/16980143/cfd59ad4-4e64-11e6-8768-3260ed2e72f1.PNG)
I put my correction into the pull request below
#14

If that good for you I hope that it can be merged soon.

Regards

**Comment by ocefpaf** [comment]
Should be fixed in #18
