### ISSUE TITLE
Pushing v0.8.1 to Pypi failed

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/branca#184]
See https://github.com/python-visualization/branca/actions/runs/12252343286

> Trusted publishing exchange failure:
> 
> OpenID Connect token retrieval failed: GitHub: missing or insufficient OIDC token permissions, the ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset
> 
> This generally indicates a workflow configuration error, such as insufficient
> permissions. Make sure that your workflow has id-token: write configured
> at the job level, e.g.:
> 
> permissions:
>   id-token: write

**Comment by Conengmo** [comment]
@ocefpaf I was looking at the differences between Branca and Folium:
- the pypi.yaml workflows are slightly different, but I don't suppose that should cause this issue
- **Branca is missing a PYPI_PASSWORD in the repository secrets** that Folium does have (see https://github.com/python-visualization/folium/settings/secrets/actions vs https://github.com/python-visualization/branca/settings/secrets/actions)

I was looking to add that secret, but I don't think I can do that. On Pypi, I'm not a maintainer of Branca. **Could you add that secret to Github** so we can try to publish this new version again?

**Comment by ocefpaf** [comment]
On it...

**Comment by ocefpaf** [comment]
I don't recall if we had a token and removed it, or if I never finished to set it up. It is working now though. I restart the same GHA and the uploaded went through.

**Comment by Conengmo** [comment]
So it was just a hiccup? 🤦‍♂️ I should have tried that already, sorry about that. Thanks for helping out!

**Comment by ocefpaf** [comment]
> So it was just a hiccup? 🤦‍♂️ I should have tried that already, sorry about that. Thanks for helping out!

Sorry, I was not clear. I had to create a token. Why it was not there? I don't know :-/

**Comment by Conengmo** [comment]
Ah okay :) well weird then! Hope it doesn't happen again.
