### ISSUE TITLE
branca html popup not working

### ISSUE THREAD

**Issue by cloud05** [python-visualization/branca#19]
As the title states, the popup function is not working as of now. "branca.element.IFrame()" doesn't work while the older folium.element.IFrame() does. Attached is the screenshot.
![branca](https://cloud.githubusercontent.com/assets/8912349/22051865/31ff5532-dd81-11e6-931a-731555adf268.PNG)

**Comment by cloud05** [comment]
This works but with the ugly iframe border.
![image](https://cloud.githubusercontent.com/assets/8912349/22051906/82f93b60-dd81-11e6-9b98-f03a49148d75.png)

**Comment by cloud05** [comment]
Nevermind, found the issue with the iframe's width and height. I just copied this code on your folium example so you might wanna change that. Thanks!

**Comment by deelaka** [comment]
@cloud05  It was supposed to be fixed with #17 but it wasn't merged, however you can get the code from there and merge it to your codebase.

**Comment by ocefpaf** [comment]
@cloud05 and @deelaka I merged #17, but I don't have time to work on a new release right now. I will try to do that next month. Hopefully incorporating #18 as well.
