### ISSUE TITLE
create an asymmetric colormap

### ISSUE THREAD

**Issue by simonegabbriellini** [python-visualization/branca#32]
I am trying to create a colormap for my data,  like:

    from branca.colormap import linear

    colormap = linear.RdBu.scale(
        df.MyValue.min(),
        df.MyValue.max())

    colormap

<img width="518" alt="zoewh" src="https://user-images.githubusercontent.com/17232086/34107730-9216f6fe-e3fd-11e7-975e-323cc1b4eaac.png">

Now what I want to achieve is to have the center of the colormap on the 0. I understand that I can convert this to step colormap like:

    colormap = colormap.to_step(index=[-200, 0, 1200])

<img width="518" alt="schermata 2017-12-16 alle 16 10 58" src="https://user-images.githubusercontent.com/17232086/34107643-5cd1395a-e3fd-11e7-9ee4-fbd055cfd49b.png">

but it's not espressive in terms of values variation, only in terms of pos/neg values. 

Is there a way to move the "center" of the colormap?

**Comment by ocefpaf** [comment]
`.to_step` is not what you want, it will make a discrete `colormap`.

It seems that what you want is something like https://matplotlib.org/users/colormapnorms.html#custom-normalization-two-linear-ranges

That would be a nice addition but it is not a priority. If you fancy a PR I'd gladly review it. However, I'm more inclined to outsource the whole colormap handling to matplotlib in the near future and depend on it.

**Comment by MalithDis** [comment]
which library include branca.colormap? matplotlib or folium
