### ISSUE TITLE
Confusing error when trying to create a LinearColormap with wrong arg type

### ISSUE THREAD

**Issue by EtienneDesticourt** [python-visualization/branca#35]
Hi,

https://github.com/python-visualization/branca/blob/9f8f2fc395e6b6e4c22d291ca0da6a26f40562c3/branca/colormap.py#L51

This line raises an ``UnboundLocalError: local variable 'color_tuple' referenced before assignment`` when x is not an expected type, it's not very informative and makes it necessary to dig in the code to figure out the real problem.  
Instead there should be an else clause that raises a ValueError of some sort to indicate x is not the right type.

Minimal example:

```python
import seaborn as sns
import branca
my_palette = sns.color_palette(["#ffffff", "#000000"])
colorscale = branca.colormap.LinearColormap(*my_palette)
```

**Comment by nanodan** [comment]
I'll fix this over the weekend.

**Comment by ocefpaf** [comment]
Looking at `my_palette` that is essentially a `list` and it would be nice if `seaborn` could make its `seaborn.palettes._ColorPalette` class return true in that case. Anyway, we should fix that. PR incoming... (Hope @nanodan doesn't mind, I want to cut a new release later today.)

**Comment by nanodan** [comment]
Go for it. I got a bit sidetracked
