### ISSUE TITLE
Version control is off

### ISSUE THREAD

**Issue by Conengmo** [python-visualization/branca#41]
I noticed two problems with version control:
* There is no branch with the 0.2 release.
* master version number 0.2, even though it has additional commits compared to the 0.2 release.

My suggestion would be to do it similarly as in folium, where each release has a branch and the master has a version number of e.g. 0.5.0+104.gbae5528. I suppose this was already the way it is supposed to be in branca.

**Comment by ocefpaf** [comment]
We are missing the `v0.2.0` tag on GitHub, probably my mistake :-(

I'm preparing a PR to use versioneer here to in order to avoid mistakes like that in the future.
