### ISSUE TITLE
Feature request: add the Viridis color scale

### ISSUE THREAD

**Issue by araichev** [python-visualization/branca#46]
After all, it is [one of the best](https://stats.stackexchange.com/a/223324) color scales.

**Comment by ocefpaf** [comment]
@araichev one can probably find the HTML definition of `viridis` online (or use matplotlib to create one) and add it here:

https://github.com/python-visualization/branca/blob/master/branca/_schemes.json

Do you want to send a PR?

**Comment by ocefpaf** [comment]
Done in #47
