### ISSUE TITLE
Encountered issue finding the _cnames.json file when running as an executable

### ISSUE THREAD

**Issue by nathan3leaf** [python-visualization/branca#54]
When I compile my script into an exe, when it is run, it throws an error that it cannot find the _cnames.json file. I verified that the file exists in the site-packages/branca folder, which is probably why the program runs fine in an IDE, but when the exe is created, it will end up looking for this file in a temp folder. I'm trying to figure out if there is a way to tell branca in my script where to look for this file so that it gets packaged with my exe or as another option, is in the same folder as my executable.

EDIT/UPDATE: In the colormap.py file, it has two absolute file references, one to '_cnames.json' and one to '_schemes.json' When the exe is created, it's looking in the temp folder, assuming it will be there. There must be some way to tell it to look in a relative path so that I can include those json files with my executable.

**Comment by ocefpaf** [comment]
This is the code that loads the data in those two files:

```python
import pkg_resources

resource_package = __name__
resource_path_cnames = '/_cnames.json'

cnames_string = pkg_resources.resource_stream(
    resource_package, resource_path_cnames).read().decode()
_cnames = json.loads(cnames_string)

```

Can you investigate if there are any limitation to using `pkg_resources` with the tools you are using to create the `exe`? I don't have a Windows platform to test and I never used any of those tools.

**Comment by ryanmccartney** [comment]
Can verify this issue still exists. On trying to turn my script into an exe it throws an exception when trying to read the `/_cnames.json` from the directory associated with the exe build.

In `branca\colormap.py`

`resource_path_cnames = '/_cnames.json'

cnames_string = pkg_resources.resource_stream(
    resource_package, resource_path_cnames).read().decode() #EXCEPTION HERE
_cnames = json.loads(cnames_string)`

May be possible to include the `.../branca` folder in the build files with the `--add-data` flag in Pyinstaller. However, it's a messy workaround.

**Comment by nathan3leaf** [comment]
@ryanmccartney 

Yes, the issue exists, though there is a workaround. First step would be to edit/create a spec file, which if you're using pyinstaller directly, you already have. 

Check out this answer, which helped me solve this problem.
https://stackoverflow.com/a/55982529/9431874
