### ISSUE TITLE
Feature request: Log scale

### ISSUE THREAD

**Issue by martinRenou** [python-visualization/branca#61]
From what I understand from the code, there is no log colormap. I will implement one locally for myself, please let me know if a PR would be appreciated.

**Comment by ocefpaf** [comment]
>  I will implement one locally for myself, please let me know if a PR would be appreciated.

Sure. That would be nice. Note that we are low on manpower to review, merge, and issue a new release quickly, but PRs are always welcomed :smile:

**Comment by Conengmo** [comment]
Since this issue is quite stale I'll close it now.
