### ISSUE TITLE
ColorMaps do not support alpha

### ISSUE THREAD

**Issue by BalthasarSchachtner** [python-visualization/branca#63]
Dear all,

I encountered that the `Colormap` does not support rendering of the alpha values of the colors supplied. Is there a specific reason why the alpha channel is dropped?

I did a quick hack to propagate the alpha values to the rendering and it seems to work in my setup:
https://github.com/BalthasarSchachtner/branca/commit/ac708586165f055c0d557635a716d51c8e720428

If you are interested in this feature, I can try to clean that up and to do a proper pull request.
Thanks for your work!

**Comment by ocefpaf** [comment]
Sure!

**Comment by Conengmo** [comment]
Can be closed since we merged https://github.com/python-visualization/branca/pull/64
