### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ocefpaf** [python-visualization/branca#7]
@BibMartin once you think it is ready let's create the release and a PyPI entry.  I can to the latter for you.

**Comment by BibMartin** [comment]
@ocefpaf I've tried to create the release branch, but it does not create any branch ; just a tag. Is that good enough ?

I planned to have a `v0.1` branch where each commit would be tagged `v0.1.0`, `v0.1.1` etc.

As for the PyPi part, I'd be interested to do it. I guess I'll need to ask for help.

**Comment by ocefpaf** [comment]
> As for the PyPi part, I'd be interested to do it. I guess I'll need to ask for help.

1. Create an account at https://pypi.python.org/pypi
2. `python setup.py register` # It will show up at https://pypi.python.org/pypi/branca
3. `python setup.py sdist --formats=gztar upload` # to upload the source distribution

That is basically it.  There are a few details here and there that I don't remember, but you'll figure it out :wink: 

Note that it is good to test the source distribution and the metadata before uploading.  I usually do a `python setup.py check`  and a `python setup.py sdist` followed by a pip install of the result to make sure everything works.

**Comment by ocefpaf** [comment]
> Is that good enough?

Yep.  That is the simplest way to do it.  Complex packages might want a more complex release process, but that is good enough for me.

**Comment by BibMartin** [comment]
I've finally created the branch `v0.1` and the release `v0.1.0`. I think this will be useful if we need to put hotfixes.

As for PyPi, I've created the repo in using (I write that for keeping a track):

    python setup.py register
Then I got the packages in doing:

    python setup.py sdist bdist_wheel
At last pushed to PyPi with:

    twine upload dist/*
(as recommended by https://packaging.python.org/en/latest/distributing/#upload-your-distributions)

@ocefpaf I've set you as owner of branca so that we can both maintain it.

**Comment by ocefpaf** [comment]
> python setup.py sdist bdist_wheel

Feeling old now :unamused: 

I cannot see it at PyPI yet.  Can you check on your end if everything when smoothly?

PS: I don't know if the `bdist_wheel` + `twine` also uploads the source distribution. If not you might consider also doing `python setup.py sdist --formats=gztar upload`.  Some tools/users need to download the source and then build.

**Comment by BibMartin** [comment]
> I cannot see it at PyPI yet. Can you check on your end if everything when smoothly?

It seems it's not found by search engine ; but you can go directly to https://pypi.python.org/pypi/branca

> PS: I don't know if the bdist_wheel + twine also uploads the source distribution. If not you might consider also doing python setup.py sdist --formats=gztar upload. Some tools/users need to download the source and then build.

It has created and uploaded a `tar.gz` ; but I didn't use the option `--formats=gztar`. I hope this is good anyway :grimacing:

**Comment by ocefpaf** [comment]
> It seems it's not found by search engine ; but you can go directly to https://pypi.python.org/pypi/branca

Looks good! But what is that 0.0.0 at the bottom coming from?

> I hope this is good anyway

That is good.  Some people like `zip` to be Windows friendly, but `tar.gz` is no longer a difficulty on Windows.

**Comment by BibMartin** [comment]
> Looks good! But what is that 0.0.0 at the bottom coming from?

This is "the text" of `CHANGES.txt`. I update this asap.

**Comment by BibMartin** [comment]
I had to do a `v0.1.1` release (you cannot delete and re-upload a release on PyPi) but it looks better.

**Comment by ocefpaf** [comment]
> you cannot delete and re-upload a release on PyPi

That was allowed in the past (man do I feel old today) but it is a good thing they no longer allow it.
