### ISSUE TITLE
py2.7 error

### ISSUE THREAD

**Issue by ThomasLecocq** [python-visualization/branca#71]
Hi,

```
  File "/tmp/easy_install-VPNeCD/branca-0.4.0/setup.py", line 41
    print(error, file=sys.stderr)  # noqa
```
raises when installing on py2.7. see:
https://travis-ci.org/ROBelgium/MSNoise/jobs/652907152#L1026

Not that I really care anymore about 2.7, but yay, just wanted to let you know.

Cheers

**Comment by Conengmo** [comment]
Hi Thomas, we just dropped support for Python 2.7 in version 0.4.0 so that's probably why you're seeing that error.

**Comment by ThomasLecocq** [comment]
ok I thought so. Thanks.
