### ISSUE TITLE
License type on pypi

### ISSUE THREAD

**Issue by Xiangyu-C** [python-visualization/branca#78]
I am not sure if it's appropriate to ask here. The license on Pypi says: "Copyright (C) 2013, Martin Journois". Since this is really open source freeware, could it be changed to something like BSD? My company scans all the pypi packages and this is blocked for download due to the license issue. Thank you.

**Comment by Conengmo** [comment]
This library is distributed under an MIT license: https://github.com/python-visualization/branca/blob/master/LICENSE.txt This is a very permissive license so I can't see how this would cause issues for you to use it in your company. Please read more about the MIT license to see what it means.

**Comment by ocefpaf** [comment]
Also, many OSS licenses have a copyright statement. That is not usual. See the first line of the MIT license template: https://opensource.org/licenses/MIT

**Comment by Xiangyu-C** [comment]
Thanks for response. I think the reason was our scan simply takes the license label from pypi and it sees it says copyright. So it's prohibited from being downloaded. Any chance the meta data could reflect the MIT license instead of the Copyright wording currently shown on Pypi?

**Comment by Conengmo** [comment]
I see what  you mean. This is what shows on the branca PyPI page:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/33519926/83268405-defd6880-a1c5-11ea-8447-ed5e2afad5b4.png">

And this is what for example shows on the Numpy PyPI page:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/33519926/83268439-ec1a5780-a1c5-11ea-8a2f-749c8e5f2d7f.png">

I reckon that we want it to say "License: MIT"
