### ISSUE TITLE
Colormap banding

### ISSUE THREAD

**Issue by Chrismarsh** [python-visualization/branca#89]
When attaching a `LinearColormap` to a `folium.raster_layers.TileLayer` map, I'm getting banding in the fill

![image](https://user-images.githubusercontent.com/630436/113350303-866f8e00-92f6-11eb-8f2b-8e35403f8afa.png)
This appears to persist across various OS and browser combinations

I'm creating the colour map as
```python
import branca.colormap as cm
import seaborn as sns

#[...]

cmap = sns.color_palette("YlGnBu", 12)
colormap = cm.LinearColormap(colors=cmap, vmin=vmin, vmax=vmax)
m.add_child(colormap)

#[...]
```
I've isolated the problem with the `rect` width being set here
https://github.com/python-visualization/branca/blob/master/branca/templates/color_scale.js#L48

For my case, this function is returning a width of ~0.8 (although each rect is slightly different widths).

If I set `width=1.5` the problem is resolved
![image](https://user-images.githubusercontent.com/630436/113350795-2e855700-92f7-11eb-9cc5-a0cd914f62c2.png)

I'm wondering if this is intended behaviour, if it's a bug, and/or if there are any unintended consequences to changing the width.

**Comment by Conengmo** [comment]
I'm not sure how this code came about and I would have to guess what is causing the banding.

For me, I don't see banding with the current code. Setting a particular width doesn't change that. If I zoom the page in I do get banding at some zoom levels, but not all.

I'm going to say this is not something we have to strive to resolve. But if somebody can provide more insight on this that is welcome!
