### ISSUE TITLE
Caption Font Size

### ISSUE THREAD

**Issue by myblackbeard** [python-visualization/branca#92]
Is there a way to increase the size of the colormap caption?

**Comment by Conengmo** [comment]
Take a look at https://github.com/python-visualization/branca/issues/91#issuecomment-1166392776, which contains a snippet to add css that affects the colormap. You could do something similar with font size probably.

**Comment by varsha2509** [comment]
Here is a solution: 
```
svg_style = '<style>svg#legend {font-size: 14px; background-color: white;}</style>'
map.get_root().header.add_child(folium.Element(svg_style))
```

You can remove the white-background if you don't need that.
