### ISSUE TITLE
Uncaught TypeError: Cannot read property 'open' of null on branca==0.4 and above

### ISSUE THREAD

**Issue by nanshanli** [python-visualization/branca#97]
Hi,

When using the following versions (`branca==0.4, folium==0.12.1`),

```python
import folium 
folium.Map()
```
gives: `Uncaught TypeError: Cannot read property 'open' of null`

Downgrading to `branca==0.3.1, folium==0.12.1` solves the problem, and the base map is rendered correctly.

Can anyone else replicate this error or know what might be the cause? I am working within a databricks notebook, on python 3.8.8.

**Comment by Conengmo** [comment]
Can you share the full stacktrace? At what line in what file does the error occur?

**Comment by nanshanli** [comment]
Unfortunately no stacktrace is produced from this error within databricks. I have also tried to look within the spark driver logs but nothing was logged at all.

![image](https://user-images.githubusercontent.com/29420804/124722554-be611f80-df3c-11eb-8cfc-140c9e297050.png)

Is there anything I can execute to test out what might be wrong?

**Comment by Conengmo** [comment]
I don't know about databricks, but given that folium is not broken in general I suspect this has something to do with your setup. Sorry that's not really helpful.

**Comment by nanshanli** [comment]
No worries - I thought it might be a problem with branca since it works when I downgrade branca to 0.3. It still works with the workaround so I am not too bothered by it.

![image](https://user-images.githubusercontent.com/29420804/124723251-6e368d00-df3d-11eb-8d54-5cf2eeabf40d.png)

**Comment by Conengmo** [comment]
Could you try installing branca from our master branch? We made a change recently that might help.

**Comment by nanshanli** [comment]
oh that's great! yes, it does work with the master branch build

![image](https://user-images.githubusercontent.com/29420804/124727179-0f731280-df41-11eb-89f5-f31874fda9a0.png)

thank you - looking forward to the release!

**Comment by Conengmo** [comment]
that's good news, thanks for verifying that
